# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9i0JPMVsE7u1MSgaijEtamjc6Z5KIr1
"""

def kasallik_tashxisi(belgi):
  if belgi == "istima":
    return "parasetamol iching"
  elif belgi == "gripp":
    return "taylol xot iching"
  elif belgi == "bosh og'rig'i":
    return "trimol iching"
  elif belgi == "tomoq og'rig'i":
    return "tanzelgon h iching"
  elif belgi == "oyoq og'rig'i":
    return "kyupen maz surting"
  elif belgi == "suyak sinishi":
    return "shifokorga murojat qiling"
  else:
    return "shifokorga murojat qiling"
belgi=input("kasallik belgisini kiriting")
natija=kasallik_tashxisi(belgi)
print(natija)

"""# Новый раздел"""